name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.4'

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libvips libglib2.0-0 libglib2.0-dev libwebp-dev libvips42 libpng-dev
        version: tests-v1
    - uses: nanasess/setup-chromedriver@v2
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-${{ matrix.ruby }}
        retention-days: 1
        path: 'spec/screenshots'
